FactoryBot.define do
  factory :card do
    account
    card_number { '4532015112830366' } # Use a consistent valid card number
    cardholder_name { 'John Doe' }
    pin { '1234' }
    cvc { '123' }
    expiration_date { 2.years.from_now.to_date }
    card_type { 'visa' }
    status { 'active' }

    # card_token and last_four_digits are auto-generated by model

    trait :visa do
      card_type { 'visa' }
      card_number { '4532015112830366' } # Valid test Visa number
    end

    trait :mastercard do
      card_type { 'mastercard' }
      card_number { '5555555555554444' } # Valid test Mastercard number
    end

    trait :discover do
      card_type { 'discover' }
      card_number { '6011111111111117' } # Valid test Discover number
    end

    trait :blocked do
      status { 'blocked' }
    end

    trait :expired do
      expiration_date { 1.year.ago.to_date }
      status { 'active' } # Keep status active, just expired by date
      skip_expiration_validation { true }
    end

    trait :suspended do
      status { 'suspended' }
    end

    trait :with_custom_pin do
      transient do
        custom_pin { '9876' }
      end

      pin { custom_pin }
    end
  end
end
